services:
  api:
    build: .
    container_name: social-api
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/social-blog
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    command: npm run dev

  mongodb:
    image: mongo:8
    container_name: social-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: social-redis
    ports:
      - "6379:6379"

volumes:
  mongo_data: